stages:
  collection:
    cmd: python src/data_collection.py
    outs:
    - data/raw/data.csv
  processing:
    cmd: python src/data_prepro.py
    deps:
    - data/raw/data.csv
    - src/data_prepro.py
    outs:
    - data/processed/processed.csv
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed/processed.csv
    - src/model_training.py

